export const PROJECT_ROUTES = {
  home: "/portfolio",
  portfolioProjects: "/portfolio#projects",
  photoGraph: "/projects/photo-graph",
  photoGraphExperience: "/projects/photo-graph/experience",
  photoGraphAdminLogin: "/admin/photo-graph/login",
  photoGraphAdminUpload: "/admin/photo-graph/upload",
  spotifyNodify: "/projects/spotify-nodify",
  spotifyNodifyExperience: "/projects/spotify-nodify/experience",
  grailedPlus: "/grailed-plus",
  grailedPlusExperience: "/grailed-plus/experience",
  grailedPlusChromeWebStore:
    "https://chromewebstore.google.com/detail/grailed-plus/bgblnhmkbofpgmibnogimfheipedkegd",
  nepobabies: "/projects/nepobabiesruntheunderground",
  nepobabiesLive: "https://thetexta.github.io/nepobabiesruntheunderground/",
  nepobabiesPreview: "https://thetexta.github.io/nepobabiesruntheunderground/",
  nepobabiesGithub: "https://github.com/TheTexta/nepobabiesruntheunderground",
  bur1alritesLive: "https://bur1alrites.vercel.app/",
  elliotMairetLive: "https://elliotmairet.vercel.app/",
  elliotMairetGithub: "https://github.com/TheTexta/elliotmairet",
} as const;
